### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by jlag34** [Johnsonec16/prj-rev-bwfs-dasmoto#4]
You did a good job on your project. Overall, you got all your elements and styles correct. Your pages were also indented which was great. In your HTML, you hit the nail right on the head and your page was flawless. Great job remembering to use wrapper divs. On your CSS, you seemed to have forgot to use of classes / setting styles on an element. Though your styles were correct a lot of the repeated. Lastly, pick a class naming convention I listed for you. All in all, nice job on this one and keep up the good work.

**Comment by Johnsonec16** [comment]
Thanks for the feedback! I'll remember this for my next project.
